server.port = 9000
server.servlet.context-path=/workintech
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=1234
logging.level.org.hibernate.orm.jdbc.bind=TRACE
logging.level.org.hibernate.SQL=DEBUG
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
spring.jpa.hibernate.ddl-auto=update
spring.security.oauth2.client.registration.github.client-id=Ov23liZDvRxxHWKvBvv4
spring.security.oauth2.client.registration.github.client-secret=34b3bdf9c64ec4356fcce3c2175d9ce1cc479cef