server.port = 9000
spring.datasource.url=jdbc:postgresql://localhost:5432/burger
spring.datasource.username=postgres
spring.datasource.password=1234
logging.level.org.hibernate.SQL=Debug
logging.level.org.hibernate.jdbc.bind=trace
server.servlet.context-path=/workintech
spring.jpa.hibernate.ddl-auto=update