server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/manav
spring.datasource.username=postgres
spring.datasource.password=1234
logging.level.org.hibernate.SQL=Debug
logging.level.org.hibernate.jdbc.bind=trace
server.servlet.context-path=/workintech
spring.jpa.hibernate.ddl-auto=create
