spring.application.name=fsweb-s17d1
server.port=8585
course.name=Spring Boot Introduction
project.developer.fullname=Omer S. Balci

spring.devtools.restart.poll-interval=1s
spring.devtools.restart.quiet-period=400
spring.devtools.restart.log-condition-evaluation-delta=true

